import type { Category, Score, Tier } from "@/domain/contracts/company";
import { categories } from "../contracts/company.ts";
import { formatEvidence } from "./evidence.ts";
import { goLiveScore } from "./go-live.ts";
import { RUBRIC_VERSION, rubric } from "./rubric.ts";
import { releaseScore } from "./releases.ts";
import { evaluateTier } from "./tier-rules.ts";

export type CategoryInput = { score: number; source: string | null; reason: string | null };

// Insert-ready row for the scores table. total is generated by Postgres and assessed_at defaults to now().
export type ScoreRow = Pick<Score, "company_id" | "rubric_version" | "tier" | `${Category}_score` | `${Category}_evidence`>;
export type AssessmentResult =
  | { ok: true; row: ScoreRow; total: number; tier: Tier; tier_reason: string }
  | { ok: false; errors: string[] };

// Timing Trigger input from the company's Workday go-live date and the link that confirms it.
export function goLiveTiming(goLiveDate: string | null, source: string | null, now: Date = new Date()): CategoryInput {
  return { ...goLiveScore(goLiveDate, now), source };
}

// Release Alignment input from the Workday release calendar and the link that confirms the release date.
export function releaseAlignment(source: string | null, now: Date = new Date()): CategoryInput {
  return { ...releaseScore(now), source };
}

// Every category that earns points must carry a source link and a one-line reason. Omitted categories score 0.
export function buildAssessment(companyId: string, input: Partial<Record<Category, CategoryInput>>): AssessmentResult {
  const errors: string[] = [];
  const scores = {} as Record<`${Category}_score`, number>;
  const evidence = {} as Record<`${Category}_evidence`, string>;
  for (const category of categories) {
    const { label, weight } = rubric[category];
    const entry = input[category];
    const score = entry?.score ?? 0;
    if (!Number.isFinite(score) || score < 0 || score > weight) errors.push(`${label} score must be between 0 and ${weight}.`);
    const formatted = formatEvidence(entry?.source, entry?.reason);
    if (score > 0 && !formatted) errors.push(`${label} evidence requires a source link and a one-line reason.`);
    scores[`${category}_score` as const] = score;
    evidence[`${category}_evidence` as const] = formatted ?? "";
  }
  if (errors.length) return { ok: false, errors };
  const { total, tier, tier_reason } = evaluateTier({ ...scores, ...evidence });
  return { ok: true, row: { company_id: companyId, rubric_version: RUBRIC_VERSION, ...scores, ...evidence, tier }, total, tier, tier_reason };
}
